[package]
name = "Rhyni"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
slint = "1.4"
tokio = { version = "1.44", features = ["full"] }
tokio-tungstenite = "*"
url = "2.5"
futures-util = "0.3"
serde_json = "1.0"
dotenvy = "0.15"

[build-dependencies]
slint-build = "1.4"
