[package]
name = "Rhyni"
version = "0.1.0"
edition = "2025"

[dependencies]
slint = "1.10"
tokio = { version = "1.44", features = ["full"] }
tokio-tungstenite = "*"
url = "2.5"
futures-util = "0.3"
serde_json = "1.0"
